
public interface MyTags {

    String CONTENT_URL = "https://www.radiantmediaplayer.com/media/bbb-360p.mp4";
    String CONTENT_URL_SMALL ="http://mirrors.standaloneinstaller.com/video-sample/small.mp4";

    
    String AD_URL_VAST_Inline_Linear_G=            "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=";
    String AD_URL_VAST_Skippable_Inline_G=         "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=";
    String AD_URL_VAST_Redirect_Linear_G=          "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirectlinear&correlator=";
    String AD_URL_VAST_Redirect_Error_G=           "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirecterror&nofb=1&correlator=";
    String AD_URL_VAST_Redirect_Broken_Fallback_G= "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirecterror&correlator=";
    String AD_URL_VAST_VPAID_Linear_G=             "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinearvpaid2js&correlator=";
    String AD_URL_VAST_VPAID_NonLinear_G=          "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinearvpaid2js&correlator=";
    String AD_URL_VAST_Nonlinear_inline_G=         "https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=";

    String AD_URL_VAST_appnexus=                   "http://lax1-ib.adnxs.com/ab?ro=1&an_audit=0&referrer=http%3A%2F%2Fa2ad75b4.ngrok.io%2Fvdo_prebid_v2%2Fpublisher%2F%3Fdebug_mode%3D1&e=wqT_3QKPCaCPBAAAAwDWAAUBCN-f9-wFELPLyrf8447RBhjVs7fK_Jux4DEqNgkAAAECCCRAEQEHEAAAJEAZEQkAIREJACkRCQAxEQmoMIHSpwY47UhA7UhIAlDLgcAuWJzxW2AAaOWljwF46KYFgAEBigEDVVNEkgUG8FKYAQGgAQGoAQGwAQC4AQPAAQTIAQLQAQDYAQDgAQDwAQCKAjt1ZignYScsIDI1Mjk4ODUsIDE1NzA2MjM0NTUpO3VmKCdyJywgOTc1MTc3NzEsIC4eAPDQkgKpAiFCem95SkFqWS1Md0tFTXVCd0M0WUFDQ2M4VnN3QURnQVFBUkk3VWhRZ2RLbkJsZ0FZUFVDYUFCd3NnUjRBb0FCc2dTSUFRS1FBUUNZQVFDZ0FRR29BUU93QVFDNUFmT3RhcVFBQUNSQXdRSHpyV3FrQUFBa1FNa0IwWlJRaWg5SDFEX1pBUUFBQUFBQUFQQV80QUVBOVFFQUFBQUFtQUlBb0FJQXRRSUFBQUFBdlFJQUFBQUE0QUlBNkFJQS1BSUFnQU1CbUFNQnFBUFkBxIh1Z01KVEVGWU1Ub3pOelUzNEFPekU0Z0VBSkFFQUpnRUFjRQldBQEIREpCBQgJARgyQVFBOFFRCQ0BAVRQZ0VBSWdGclIwLpoCiQEhRGctOUN3Ni0BJG5QRmJJQVFvQUQVWAxrUURvMoUAEFFMTVRTEVgMUEFfVREMDEFBQVcdDABZHQwAYR0MAGMdDPBJZUFBLsICOGh0dHA6Ly9wcmViaWQub3JnL2Rldi1kb2NzL3Nob3ctb3V0c3RyZWFtLXZpZGVvLWFkcy5odG1s2AIA4AKtmEjqAj4NQ1RhMmFkNzViNC5uZ3Jvay5pby92ZG9fCVnYX3YyL3B1Ymxpc2hlci8_ZGVidWdfbW9kZT0x8gITCg9DVVNUT01fTU9ERUxfSUQSAPICGgoWQy4WACBMRUFGX05BTUUBHQgeChoyMwDwQ0xBU1RfTU9ESUZJRUQSAIADAIgDAZADAJgDF6ADAaoDAMAD4KgByAMA2AOcs5MB4AMA6AMA-AMBgAQAkgQNL3V0L3YzLQTwYZgEAKIEDTkxLjIwNy4xNzUuODOoBJPZBrIEEggEEAQYpgQgtgIoASgCMAA4A7gEAMAEAMgEANIEDjkzMjUjTEFYMTozNzU32gQCCAHgBADwBMuBwC6IBQGYBQCgBf______AQMYAcAFAMkFAAUBFPA_0gUJCQULfAAAANgFAeAFAfAFw5UL-gUECAAQAJAGAZgGALgGAMEGASE8AADwP8gGANAG9S_aBhYKEAkUGQFQEAAYAOAGBPIGAggAgAcBiAcAoAdA&s=2f5f4d139be3cc9368f72b6c6e04cec1ce56b020";
    String AD_URL_VAST_pocketmath=                 "https://vast.richmediaads.com/vast.php?xmlpath=taggenerator/vast-xml/PocketMath1570830688875.xml&pageLoadId=${imp_id}&cb=${imp_id}&dsp=pocketmath&exchange=${exchange}&inventory=${source_id}&uniqueId=${device_identifier}&ct=${click_url}";
    String Ad_URL_VAST_appier=                     "https://vast.richmediaads.com/vast.php?xmlpath=taggenerator/vast-xml/Appier1570830792013.xml&pageLoadId=&cb=&dsp=appier&exchange=Appier&inventory=${channel_id}&uniqueId=${mac}&ct=";
    String Ad_URL_VAST_bidstalk=                   "https://vast.richmediaads.com/vast.php?xmlpath=taggenerator/vast-xml/Bidstalk1570831217010.xml&pageLoadId={CACHEBUSTER}&cb={CACHEBUSTER}&dsp=bidstalk&exchange={EXCHANGE_NAME}&inventory={APP_NAME}&uniqueId={DEVICE_PLATFORM_ID}&ct={CLICK_URL}";


    String AD_URL_VMAP_VDO = "http://vdo.ai/sample/floating/ads_vmap.php";

    String AD_URL_VMAP_G1  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G2  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostoptimizedpod&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G3  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G4  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostoptimizedpodbumper&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G5  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator=";
    String AD_URL_VMAP_G6  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G7  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonly&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G8  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonlybumper&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G9  = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G10 = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonlybumper&cmsid=496&vid=short_onecue&correlator=";
    String AD_URL_VMAP_G11 = "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=";
    

}
